services:
  redis:
    image: redis
    volumes:
     - ./data/redis/:/data/
    restart: always
    command: redis-server --dir /data --save 60 1 --loglevel warning
    ports:
      - 6379:6379

  python:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    image: github.com/valdeir027/docker/python:latest

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
    volumes:
     - ./media/:/app/src/media/
    ports:
      - 8000:8000
    depends_on:
      - python
      - redis
    env_file:
      - ./.env
