services:
  python:
    build:
        args:
          requirements: local
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
  web:
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
     - ./data/:/app/src/data/
     - .:/app/src/
    ports:
      - 8000:8000